package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseEnclosure;

/**
 * Generated by Jboot.
 */
@Table(tableName = "enclosure", primaryKey = "enclosure_id")
public class Enclosure extends BaseEnclosure<Enclosure> {
	
}
