package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseInstitutionDetailInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "institution_detail_info", primaryKey = "wd_id")
public class InstitutionDetailInfo extends BaseInstitutionDetailInfo<InstitutionDetailInfo> {
	
}
