package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseInstitutionInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "institution_info", primaryKey = "institution_id")
public class InstitutionInfo extends BaseInstitutionInfo<InstitutionInfo> {
	
}
