package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServiceOrderEnclosure<M extends BaseServiceOrderEnclosure<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "ServiceOrderEnclosure:add";
    public static final String ACTION_DELETE = "ServiceOrderEnclosure:delete";
    public static final String ACTION_UPDATE = "ServiceOrderEnclosure:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setOrderEnclosureId(java.lang.String orderEnclosureId) {
		set("order_enclosure_id", orderEnclosureId);
	}
	
	public java.lang.String getOrderEnclosureId() {
		return getStr("order_enclosure_id");
	}

	public void setOrderEnclosurePhoto(java.lang.String orderEnclosurePhoto) {
		set("order_enclosure_photo", orderEnclosurePhoto);
	}
	
	public java.lang.String getOrderEnclosurePhoto() {
		return getStr("order_enclosure_photo");
	}

	public void setOrderEnclosureUpTime(java.lang.String orderEnclosureUpTime) {
		set("order_enclosure_up_time", orderEnclosureUpTime);
	}
	
	public java.lang.String getOrderEnclosureUpTime() {
		return getStr("order_enclosure_up_time");
	}

}
