package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseCommodityInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "commodity_info", primaryKey = "commodity_id")
public class CommodityInfo extends BaseCommodityInfo<CommodityInfo> {
	
}
