package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseContract;

/**
 * Generated by Jboot.
 */
@Table(tableName = "contract", primaryKey = "contract_id")
public class Contract extends BaseContract<Contract> {
	
}
