package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseServiceOrderEnclosure;

/**
 * Generated by Jboot.
 */
@Table(tableName = "service_order_enclosure", primaryKey = "order_enclosure_id")
public class ServiceOrderEnclosure extends BaseServiceOrderEnclosure<ServiceOrderEnclosure> {
	
}
