package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseServiceOrder;

/**
 * Generated by Jboot.
 */
@Table(tableName = "service_order", primaryKey = "service_order_id")
public class ServiceOrder extends BaseServiceOrder<ServiceOrder> {
	
}
