package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseStaffInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "staff_info", primaryKey = "staff_id")
public class StaffInfo extends BaseStaffInfo<StaffInfo> {
	
}
