package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseSupplierInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "supplier_info", primaryKey = "supplier_id")
public class SupplierInfo extends BaseSupplierInfo<SupplierInfo> {
	
}
