package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseWaregouseOut;

/**
 * Generated by Jboot.
 */
@Table(tableName = "waregouse_out", primaryKey = "equip_id")
public class WaregouseOut extends BaseWaregouseOut<WaregouseOut> {
	
}
