package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseWlUse;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wl_use", primaryKey = "wl_id")
public class WlUse extends BaseWlUse<WlUse> {
	
}
