package kw.test.model;

import io.jboot.db.annotation.Table;
import kw.test.model.base.BaseUser03;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user03", primaryKey = "id")
public class User03 extends BaseUser03<User03> {
	
}
