package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServiceOrder<M extends BaseServiceOrder<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "ServiceOrder:add";
    public static final String ACTION_DELETE = "ServiceOrder:delete";
    public static final String ACTION_UPDATE = "ServiceOrder:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setServiceOrderId(java.lang.String serviceOrderId) {
		set("service_order_id", serviceOrderId);
	}
	
	public java.lang.String getServiceOrderId() {
		return getStr("service_order_id");
	}

	public void setServiceOrderName(java.lang.String serviceOrderName) {
		set("service_order_name", serviceOrderName);
	}
	
	public java.lang.String getServiceOrderName() {
		return getStr("service_order_name");
	}

	public void setWdName(java.lang.String wdName) {
		set("wd_name", wdName);
	}
	
	public java.lang.String getWdName() {
		return getStr("wd_name");
	}

	public void setJiaOfficial(java.lang.String jiaOfficial) {
		set("jia_official", jiaOfficial);
	}
	
	public java.lang.String getJiaOfficial() {
		return getStr("jia_official");
	}

	public void setServiceOrderStartTime(java.util.Date serviceOrderStartTime) {
		set("service_order_start_time", serviceOrderStartTime);
	}
	
	public java.util.Date getServiceOrderStartTime() {
		return get("service_order_start_time");
	}

	public void setRepairCost(java.math.BigDecimal repairCost) {
		set("repair_cost", repairCost);
	}
	
	public java.math.BigDecimal getRepairCost() {
		return get("repair_cost");
	}

	public void setOrderCategory(java.lang.String orderCategory) {
		set("order_category", orderCategory);
	}
	
	public java.lang.String getOrderCategory() {
		return getStr("order_category");
	}

	public void setOrderWorkTime(java.util.Date orderWorkTime) {
		set("order_work_time", orderWorkTime);
	}
	
	public java.util.Date getOrderWorkTime() {
		return get("order_work_time");
	}

	public void setOrderFinshTime(java.util.Date orderFinshTime) {
		set("order_finsh_time", orderFinshTime);
	}
	
	public java.util.Date getOrderFinshTime() {
		return get("order_finsh_time");
	}

	public void setOrderStatus(java.lang.String orderStatus) {
		set("order_status", orderStatus);
	}
	
	public java.lang.String getOrderStatus() {
		return getStr("order_status");
	}

	public void setOrderEnclosureId(java.lang.String orderEnclosureId) {
		set("order_enclosure_id", orderEnclosureId);
	}
	
	public java.lang.String getOrderEnclosureId() {
		return getStr("order_enclosure_id");
	}

	public void setServiceOrderInstitution(java.lang.String serviceOrderInstitution) {
		set("service_order_institution", serviceOrderInstitution);
	}
	
	public java.lang.String getServiceOrderInstitution() {
		return getStr("service_order_institution");
	}

	public void setRapairStaff(java.lang.String rapairStaff) {
		set("rapair_staff", rapairStaff);
	}
	
	public java.lang.String getRapairStaff() {
		return getStr("rapair_staff");
	}

}
