package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContract<M extends BaseContract<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Contract:add";
    public static final String ACTION_DELETE = "Contract:delete";
    public static final String ACTION_UPDATE = "Contract:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setContractId(java.lang.String contractId) {
		set("contract_id", contractId);
	}
	
	public java.lang.String getContractId() {
		return getStr("contract_id");
	}

	public void setContractName(java.lang.String contractName) {
		set("contract_name", contractName);
	}
	
	public java.lang.String getContractName() {
		return getStr("contract_name");
	}

	public void setContractStartDate(java.util.Date contractStartDate) {
		set("contract_start_date", contractStartDate);
	}
	
	public java.util.Date getContractStartDate() {
		return get("contract_start_date");
	}

	public void setContractEndDate(java.util.Date contractEndDate) {
		set("contract_end_date", contractEndDate);
	}
	
	public java.util.Date getContractEndDate() {
		return get("contract_end_date");
	}

	public void setContractMoney(java.math.BigDecimal contractMoney) {
		set("contract_money", contractMoney);
	}
	
	public java.math.BigDecimal getContractMoney() {
		return get("contract_money");
	}

	public void setContractContent(java.lang.String contractContent) {
		set("contract_content", contractContent);
	}
	
	public java.lang.String getContractContent() {
		return getStr("contract_content");
	}

	public void setInstinitionId(java.lang.String instinitionId) {
		set("instinition_id", instinitionId);
	}
	
	public java.lang.String getInstinitionId() {
		return getStr("instinition_id");
	}

	public void setWdId(java.lang.String wdId) {
		set("wd_id", wdId);
	}
	
	public java.lang.String getWdId() {
		return getStr("wd_id");
	}

	public void setJiaLead(java.lang.String jiaLead) {
		set("jia_lead", jiaLead);
	}
	
	public java.lang.String getJiaLead() {
		return getStr("jia_lead");
	}

	public void setInstallDate(java.util.Date installDate) {
		set("install_date", installDate);
	}
	
	public java.util.Date getInstallDate() {
		return get("install_date");
	}

	public void setEnter(java.lang.String enter) {
		set("enter", enter);
	}
	
	public java.lang.String getEnter() {
		return getStr("enter");
	}

	public void setEnterDate(java.util.Date enterDate) {
		set("enter_date", enterDate);
	}
	
	public java.util.Date getEnterDate() {
		return get("enter_date");
	}

	public void setContractStatus(java.lang.String contractStatus) {
		set("contract_status", contractStatus);
	}
	
	public java.lang.String getContractStatus() {
		return getStr("contract_status");
	}

}
