package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaffInfo<M extends BaseStaffInfo<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "StaffInfo:add";
    public static final String ACTION_DELETE = "StaffInfo:delete";
    public static final String ACTION_UPDATE = "StaffInfo:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setStaffId(java.lang.String staffId) {
		set("staff_id", staffId);
	}
	
	public java.lang.String getStaffId() {
		return getStr("staff_id");
	}

	public void setStaffName(java.lang.String staffName) {
		set("staff_name", staffName);
	}
	
	public java.lang.String getStaffName() {
		return getStr("staff_name");
	}

	public void setStaffBirthday(java.util.Date staffBirthday) {
		set("staff_birthday", staffBirthday);
	}
	
	public java.util.Date getStaffBirthday() {
		return get("staff_birthday");
	}

	public void setStaffTel(java.lang.String staffTel) {
		set("staff_tel", staffTel);
	}
	
	public java.lang.String getStaffTel() {
		return getStr("staff_tel");
	}

	public void setStaffAddress(java.lang.String staffAddress) {
		set("staff_address", staffAddress);
	}
	
	public java.lang.String getStaffAddress() {
		return getStr("staff_address");
	}

	public void setStaffCategory(java.lang.String staffCategory) {
		set("staff_category", staffCategory);
	}
	
	public java.lang.String getStaffCategory() {
		return getStr("staff_category");
	}

	public void setStaffPhoto(java.lang.String staffPhoto) {
		set("staff_photo", staffPhoto);
	}
	
	public java.lang.String getStaffPhoto() {
		return getStr("staff_photo");
	}

	public void setStaffStatus(java.lang.String staffStatus) {
		set("staff_status", staffStatus);
	}
	
	public java.lang.String getStaffStatus() {
		return getStr("staff_status");
	}

}
