package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWlUse<M extends BaseWlUse<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "WlUse:add";
    public static final String ACTION_DELETE = "WlUse:delete";
    public static final String ACTION_UPDATE = "WlUse:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setWlId(java.lang.String wlId) {
		set("wl_id", wlId);
	}
	
	public java.lang.String getWlId() {
		return getStr("wl_id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setWlName(java.lang.String wlName) {
		set("wl_name", wlName);
	}
	
	public java.lang.String getWlName() {
		return getStr("wl_name");
	}

}
