package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaregouseOut<M extends BaseWaregouseOut<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "WaregouseOut:add";
    public static final String ACTION_DELETE = "WaregouseOut:delete";
    public static final String ACTION_UPDATE = "WaregouseOut:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setEquipId(java.lang.String equipId) {
		set("equip_id", equipId);
	}
	
	public java.lang.String getEquipId() {
		return getStr("equip_id");
	}

	public void setEquipType(java.lang.String equipType) {
		set("equip_type", equipType);
	}
	
	public java.lang.String getEquipType() {
		return getStr("equip_type");
	}

	public void setEquipXinghao(java.lang.String equipXinghao) {
		set("equip_xinghao", equipXinghao);
	}
	
	public java.lang.String getEquipXinghao() {
		return getStr("equip_xinghao");
	}

	public void setEquipName(java.lang.String equipName) {
		set("equip_name", equipName);
	}
	
	public java.lang.String getEquipName() {
		return getStr("equip_name");
	}

	public void setEquipInDate(java.util.Date equipInDate) {
		set("equip_in_date", equipInDate);
	}
	
	public java.util.Date getEquipInDate() {
		return get("equip_in_date");
	}

	public void setEquipStatus(java.lang.String equipStatus) {
		set("equip_status", equipStatus);
	}
	
	public java.lang.String getEquipStatus() {
		return getStr("equip_status");
	}

	public void setEquipLqLead(java.lang.String equipLqLead) {
		set("equip_lq_lead", equipLqLead);
	}
	
	public java.lang.String getEquipLqLead() {
		return getStr("equip_lq_lead");
	}

	public void setEquipLqDate(java.util.Date equipLqDate) {
		set("equip_lq_date", equipLqDate);
	}
	
	public java.util.Date getEquipLqDate() {
		return get("equip_lq_date");
	}

	public void setEquipLead(java.lang.String equipLead) {
		set("equip_lead", equipLead);
	}
	
	public java.lang.String getEquipLead() {
		return getStr("equip_lead");
	}

	public void setEquipOutDate(java.util.Date equipOutDate) {
		set("equip_out_date", equipOutDate);
	}
	
	public java.util.Date getEquipOutDate() {
		return get("equip_out_date");
	}

	public void setHetong(java.lang.String hetong) {
		set("hetong", hetong);
	}
	
	public java.lang.String getHetong() {
		return getStr("hetong");
	}

}
