package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEnclosure<M extends BaseEnclosure<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Enclosure:add";
    public static final String ACTION_DELETE = "Enclosure:delete";
    public static final String ACTION_UPDATE = "Enclosure:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setEnclosureId(java.lang.String enclosureId) {
		set("enclosure_id", enclosureId);
	}
	
	public java.lang.String getEnclosureId() {
		return getStr("enclosure_id");
	}

	public void setContractId(java.lang.String contractId) {
		set("contract_id", contractId);
	}
	
	public java.lang.String getContractId() {
		return getStr("contract_id");
	}

	public void setImagePath(java.lang.String imagePath) {
		set("image_path", imagePath);
	}
	
	public java.lang.String getImagePath() {
		return getStr("image_path");
	}

}
