package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierInfo<M extends BaseSupplierInfo<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "SupplierInfo:add";
    public static final String ACTION_DELETE = "SupplierInfo:delete";
    public static final String ACTION_UPDATE = "SupplierInfo:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setSupplierId(java.lang.String supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.String getSupplierId() {
		return getStr("supplier_id");
	}

	public void setSupplierName(java.lang.String supplierName) {
		set("supplier_name", supplierName);
	}
	
	public java.lang.String getSupplierName() {
		return getStr("supplier_name");
	}

	public void setSupplierAddress(java.lang.String supplierAddress) {
		set("supplier_address", supplierAddress);
	}
	
	public java.lang.String getSupplierAddress() {
		return getStr("supplier_address");
	}

	public void setSupplierLead(java.lang.String supplierLead) {
		set("supplier_lead", supplierLead);
	}
	
	public java.lang.String getSupplierLead() {
		return getStr("supplier_lead");
	}

	public void setSupplierTel(java.lang.String supplierTel) {
		set("supplier_tel", supplierTel);
	}
	
	public java.lang.String getSupplierTel() {
		return getStr("supplier_tel");
	}

	public void setSupplierRemark(java.lang.String supplierRemark) {
		set("supplier_remark", supplierRemark);
	}
	
	public java.lang.String getSupplierRemark() {
		return getStr("supplier_remark");
	}

}
